### ISSUE TITLE
Include LICENSE file in plugin template

### ISSUE THREAD

**Issue by corneliusweig** [replicatedhq/krew-plugin-template#3]
While reviewing https://github.com/kubernetes-sigs/krew-index/pull/365, I noticed that this template got out of sync with what we recommend in https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md#writing-a-plugin-manifest. In particular, it does not install a LICENSE file, which we now require.

Besides, I'm wondering if you could include the descriptive comments for the manifest fields in your template. Of course, these should be removed before submitting the template, but it could help plugin authors to get started. WDYT?

**Comment by marccampbell** [comment]
👍 makes sense to me. cc @laverya

**Comment by bergerx** [comment]
This issue is solved by #4.

**Comment by corneliusweig** [comment]
Thanks for implementing our best practices in your template repo! ❤️
