### ISSUE TITLE
update github action

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/krew-plugin-template#6]
An example of a working action is: https://github.com/marccampbell/kubectl-alias/blob/3a7656fe2996d0e6ac34d9c096ac18787e076349/.github/workflows/build-test-deploy.yaml

The current action is HCL based and does not work.

(The above link is not valid, a slightly more complex one is at https://github.com/replicatedhq/kots/blob/master/.github/workflows/deploy.yaml)

**Comment by rajatjindal** [comment]
Hi, thank you for this template repo. 

I just stumbled upon this issue. I couldn’t see the link above (may b a private repo?) so not sure how is that implemented.

But i wanted to take this issue as an opportunity to tell u about github.com/rajatjindal/krew-release-bot (disclaimer: I implemented that). And a sample implementation: https://github.com/rajatjindal/kubectl-whoami/blob/master/.github/workflows/release.yml using that.

A few plugins are already using this for publishing releases automatically and its also documented as part of krew docs.

Request you to please consider that as the github action to do automated releases as part of this template repo. I am happy to answer any questions/concerns u might have

cc: @ahmetb

Many thanks
Rajat Jindal

**Comment by marccampbell** [comment]
Thanks @rajatjindal 

I updated the example with a different URL that works.

But we don't push to krew, so this idea makes sense to me. The workflow in kubectl-whoami looks like a great model

**Comment by rajatjindal** [comment]
thats great. if its acceptable, can i submit PR for this repo to use krew-release-bot?

**Comment by marccampbell** [comment]
Please!
